# Site wide configuration

title:            //__devops_life__// Ramblings around Cloud, DevOps, SE, ...
locale:           en_US
#url:              http://www.devopslife.com/


# Jekyll configuration

permalink:   /:year/:month/:day/:title.html
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Florian Rosenberg
  avatar: bio-photo.jpg
  bio: "Software engineer, Researcher, DevOps enthusiat at IBM"
  email: #f.rosenberg@gmail.com
  disqus-shortname: frosenberg
  twitter: ponifaax
  facebook: frosenberg
  google:
    plus:
    analytics: UA-53838963-1
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: frosenberg
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: florianrosenberg
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
